name: Shellcheck

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'ra/**'
      - 'alerts/**'
      - 'tools/**'
      - 'scripts/**'
  pull_request:
    branches: [main]
    paths:
      - 'ra/**'
      - 'alerts/**'
      - 'tools/**'
      - 'scripts/**'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run
        run: |
          find ra alerts tools -type f \
            -exec awk '/^#!.*bash/{print FILENAME} {nextfile}' {} + \
            | xargs shellcheck -P ra/ -a -x -s bash
